name: Сборка Android-приложения

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Декодирование ключа подписи
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > ${{ github.workspace }}/app/napominalka-key.jks

      - name: Сделать gradlew исполняемым
        run: chmod +x gradlew

      # ----- ВОТ ИЗМЕНЕННЫЙ ШАГ -----
      - name: Очистка и сборка Release APK с помощью Gradle
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        # Мы добавили 'clean' перед 'assembleRelease'
        run: ./gradlew clean assembleRelease

      - name: Загрузить артефакт (Release APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
