# Название вашего рабочего процесса. Оно будет отображаться во вкладке Actions
name: Сборка Android-приложения

# Триггеры для запуска:
on:
  # 1. Запускать при каждом push в ветку 'main'
  push:
    branches: [ "main" ]
  # 2. Позволяет запускать этот процесс вручную из вкладки Actions
  workflow_dispatch:

# Задачи, которые будут выполняться
jobs:
  build:
    # Используем последнюю версию Ubuntu для сборки
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование вашего репозитория
      # Этот шаг загружает ваш код в виртуальную машину, где будет происходить сборка
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      # Шаг 2: Настройка среды Java (JDK)
      # Android-приложения требуют определенной версии Java для сборки. 17 — хороший выбор для современных проектов.
      - name: Настройка JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Шаг 3: Предоставление прав на выполнение для Gradle Wrapper
      # Это важный шаг, который предотвращает ошибку "permission denied"
      - name: Сделать gradlew исполняемым
        run: chmod +x gradlew

      # Шаг 4: Сборка debug-версии APK
      # Эта команда запускает сборку. Мы собираем 'debug', так как для этого не требуются ключи подписи.
      - name: Сборка с помощью Gradle
        run: ./gradlew assembleDebug

      # Шаг 5: Загрузка APK-файла как артефакта
      # Этот шаг берет собранный APK и сохраняет его, чтобы вы могли его скачать.
      - name: Загрузить артефакт (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk # Имя файла, который вы увидите при скачивании
          path: app/build/outputs/apk/debug/app-debug.apk # Путь, где лежит собранный APK
