# Название вашего рабочего процесса
name: Сборка Android-приложения

# Триггеры для запуска
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Задачи, которые будут выполняться
jobs:
  build:
    # Используем последнюю версию Ubuntu для сборки
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование вашего репозитория
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      # Шаг 2: Настройка среды Java (JDK)
      # ----- ГЛАВНОЕ ИЗМЕНЕНИЕ: Мы удалили строку "cache: 'gradle'" -----
      - name: Настройка JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      # Шаг 3: Декодирование ключа подписи
      - name: Декодирование ключа подписи
        env:
          KEYSTORE_BASE_64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE_64 | base64 --decode > ${{ github.workspace }}/app/napominalka-key.jks

      # Шаг 4: Предоставление прав на выполнение для Gradle Wrapper
      - name: Сделать gradlew исполняемым
        run: chmod +x gradlew

      # Шаг 5: Очистка и сборка Release APK
      - name: Сборка приложения
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        # Мы также убрали --stacktrace, так как он больше не нужен
        run: ./gradlew clean assembleRelease

      # Шаг 6: Загрузка APK-файла как артефакта
      - name: Загрузить артефакт (Release APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
